version: '3.1'
services:
  api:
    image: lodcat.api
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DB: ${DB_DB}
      DB_HOST: db
    ports:
      - 80:80
  db:
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    ports:
      - 5432:5432
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: lodcat_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
