#!/bin/sh
set -eu

LODCAT_DIR="$(dirname $(realpath $0))"
set -a; . "$LODCAT_DIR"/.env; set +a

/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xmx8g -cp .:lodcat.model/target/lodcat.model.jar org.dice_research.lodcat.model.WikipediaCorpusPartitioner "$@"
