#!/bin/sh
set -eu

LODCAT_DIR="$(dirname $(realpath $0))"
set -a; . "$LODCAT_DIR"/.env; set +a

OBJECT_FILE="$1"
OUTPUT_DIR="$2"
REPEATS="$3"
JOBS="$4"
THREADS_PER_PROCESS="$5"

make palmetto-0.1.0.jar palmetto-indexes

mkdir -p "$OUTPUT_DIR"/logs

parallel --jobs "$JOBS" --tag --verbose --results "$OUTPUT_DIR"/logs --joblog "$OUTPUT_DIR"/logs/joblog \
"$LODCAT_DIR"/lodcat-quality-number-instance "$OBJECT_FILE" "$OUTPUT_DIR"/data "$THREADS_PER_PROCESS" {2} {1} \
::: $(seq 1 $REPEATS) \
::: 50 75 100 125 150 200 300
