#!/bin/bash
set -eu

function cleanup {
    docker rm netl
}

trap cleanup EXIT

LODCAT_DIR="$(dirname $(realpath $0))"
MODEL_DIR="$1"

"$LODCAT_DIR"/topwords4labelling <"$MODEL_DIR"/top_words.csv >"$MODEL_DIR"/top_words.labelling
docker run \
-v "$(realpath "$MODEL_DIR")"/top_words.labelling:/data/topics.csv \
--name netl dicegroup/netl
docker cp netl:/usr/src/app/model_run/output_unsupervised "$MODEL_DIR"/labels-unsupervised.csv
docker cp netl:/usr/src/app/model_run/output_supervised "$MODEL_DIR"/labels-supervised.csv
