#!/bin/bash
set -eu

LODCAT_DIR="$(dirname $(realpath $0))"
set -a; . "$LODCAT_DIR"/.env; set +a

MODEL_DIR="$1"
OBJECT_FILE="$2"
OUTPUT_FILE="$3"

$CLASSIFIER "$MODEL_DIR/model.gz" "$OBJECT_FILE" "$OUTPUT_FILE"
