#!/bin/sh
set -eu

set -a; . ./.env; set +a

OUTPUT_DIR=$1

for QUALITY in C_P C_V2; do
    truncate -s 0 "$OUTPUT_DIR/micro-quality-$QUALITY.csv"
    for NUMBER_DIR in "$OUTPUT_DIR"/*; do
        if [ -d "$NUMBER_DIR" ]; then
            rm -f "$NUMBER_DIR/micro-quality-$QUALITY.csv"
            for MODEL_DIR in "$NUMBER_DIR"/*; do
                if [ -d "$MODEL_DIR" ]; then
                    if [ -f "$MODEL_DIR/quality-$QUALITY.csv" ]; then
                        cat "$MODEL_DIR/quality-$QUALITY.csv" >>"$NUMBER_DIR/micro-quality-$QUALITY.csv"
                    else
                        echo "Missing file: $MODEL_DIR/quality-$QUALITY.csv"
                    fi
                fi
            done
            if [ -f "$NUMBER_DIR/micro-quality-$QUALITY.csv" ]; then
                echo $(basename "$NUMBER_DIR"), $(octave -f -q --eval "X = csvread('$NUMBER_DIR/micro-quality-$QUALITY.csv'); disp(mean(X));"), $(octave -f -q --eval "X = csvread('$NUMBER_DIR/micro-quality-$QUALITY.csv'); disp(std(X));"), $(find "$NUMBER_DIR" -mindepth 1 -maxdepth 1 -type d |wc -l) >>"$OUTPUT_DIR/micro-quality-$QUALITY.csv"
            fi
        fi
    done

    echo Best model $QUALITY: $(octave -f -q --eval "X = csvread('$OUTPUT_DIR/micro-quality-$QUALITY.csv'); [w, iw] = max(X(:,2)); disp(X(iw,:))")
done

echo "
set terminal png
set output '$OUTPUT_DIR/micro-quality.png'
set title 'Micro-average topic quality (LODCat)'
set xlabel 'Number of topics'
set ylabel 'Micro-average topic quality'
set grid
set key outside center bottom
set logscale x
set xrange [1:]
set yrange [0:1]
set style line 1 lc rgb '#0060ad' pt 7 ps 1.5 lt 1 lw 2
plot '$OUTPUT_DIR/micro-quality-C_P.csv' using 1:2:3 title 'C_P' ls 1 with errorbars, \
     '$OUTPUT_DIR/micro-quality-C_V2.csv' using 1:2:3 title 'C_V2' ls 2 with errorbars
" |gnuplot
