#!/bin/sh
set -eu

LODCAT_DIR="$(dirname $(realpath $0))"
set -a; . "$LODCAT_DIR"/.env; set +a

INPUT_DIR=$1
OUTPUT_DIR=$2
JOBS=$3

mkdir -p "$OUTPUT_DIR"/logs

parallel --jobs "$JOBS" --tag --verbose --results "$OUTPUT_DIR/logs" --joblog "$OUTPUT_DIR"/logs/joblog \
"$RDF_SIZE_REPORTER" "$INPUT_DIR" "$OUTPUT_DIR"/data/"{1}".csv "{1}" \
::: 0 1 2 3 4 5 6 7 8 9 a b c d e f
