#!/bin/sh
set -eu

LODCAT_DIR="$(dirname $(realpath $0))"
set -a; . "$LODCAT_DIR"/.env; set +a

INPUT_DIR=$1
OUTPUT_DIR=$2
DOC_PER_PART=$3
JOBS=$4

mkdir -p "$OUTPUT_DIR"

find "$INPUT_DIR" -type f -name '*.xml' -print0 \
|parallel -0 --jobs "$JOBS" --tag --verbose --results "$OUTPUT_DIR/results" \
"$CORPUS_PARTITIONER" "{1}" "$OUTPUT_DIR"/"{1}".parts "$DOC_PER_PART"
