#!/usr/bin/env perl
use strict;
use warnings;

$" = ",";

my @topics = split /;/, <>;
my @lines;
while (<>) {
    chomp;
    push @lines, [split /;/];
}

my $term = 0;
print "topic_id";
for (@lines) {
    print ",term", $term++;
}
print "\n";

my $topicID = 0;
for (@topics) {
    my @words = map { shift @$_ } @lines;
    /^topic/ and do {
        print "$topicID,@words\n";
        $topicID++;
    }
}
