#!/usr/bin/env python3
from dicetopicmodelingxmlcorpus import DiceTopicModelingXmlCorpus
import argparse
import logging
import os

logging.basicConfig(level=logging.DEBUG)

parser = argparse.ArgumentParser()
parser.add_argument('--input', dest='input_file', required=True, help='corpus xml file')
parser.add_argument('--output', dest='output_file', required=True, help='output dictionary file')
args = parser.parse_args()

corpus = DiceTopicModelingXmlCorpus(args.input_file)

os.makedirs(os.path.dirname(args.output_file), exist_ok=True)

corpus.init_dictionary()
logging.info('Dictionary: %s', corpus.dictionary)

corpus.dictionary.save(args.output_file)
