#!/usr/bin/env python3
from gensim.models import LdaModel
import argparse
import logging
import os

MODEL_FILE = 'gensim-ldamodel'

logging.basicConfig(level=logging.DEBUG)

parser = argparse.ArgumentParser()
parser.add_argument('--model-dir', dest='model_dir', required=True, help='model dir')
args = parser.parse_args()

model_file = os.path.join(args.model_dir, MODEL_FILE)
model = LdaModel.load(model_file)
logging.info(f'Model: {model}')
